#Homer Optimization

#python3 experiments_Homer.py -o opt -T OrtuNN -e 48 /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/optimization_Homer_48_NRC_no_lemma.txt
#python3 experiments_Homer.py -o opt -T OrtuNN -e 48 /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/optimization_Homer_48_NRC_lemma.txt

#python3 experiments_Homer.py -o opt -T SOEmotionsNN -e 48 /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/optimization_Homer_48_NRC_SONN_no_lemma.txt
#python3 experiments_Homer.py -o opt -T SOEmotionsNN -e 48 /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/optimization_Homer_48_NRC_SONN_lemma.txt

#python3 experiments_Homer.py -o opt -T OrtuNN -e 53 /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/optimization_Homer_53_Sentic_OrtuNN_no_lemma.txt


#Homer Training

#python3 experiments_Homer.py -o train -T OrtuNN -e 48 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/
#python3 experiments_Homer.py -o train -T OrtuNN -e 48 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/

#python3 experiments_Homer.py -o train -T OrtuNN -e 53 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/
#python3 experiments_Homer.py -o train -T OrtuNN -e 53 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/


#python3 experiments_Homer.py -o train -T SOEmotionsNN -e 48 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/
#python3 experiments_Homer.py -o train -T SOEmotionsNN -e 48 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/

#python3 experiments_Homer.py -o train -T SOEmotionsNN -e 53 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/
#python3 experiments_Homer.py -o train -T SOEmotionsNN -e 53 -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/

#Homer Testing

#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/
#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/

#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/
#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/


#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/
#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/

#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/
#python3 experiments_Homer.py -o test -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/
#python3 experiments_Homer.py -o test -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/


#Predict
python3 experiments_Homer.py -o predict -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/
python3 experiments_Homer.py -o predict -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M NRC_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/
python3 experiments_Homer.py -o predict -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/
python3 experiments_Homer.py -o predict -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M NRC_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/NRC_NRCIntensity/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/

python3 experiments_Homer.py -o predict -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/
python3 experiments_Homer.py -o predict -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/No_Lemma/ -M Sentic_SONN_homer_no_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/No_Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/
python3 experiments_Homer.py -o predict -t OrtuNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/
python3 experiments_Homer.py -o predict -t SOEmotionsNN -m /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Models/NoNeutral/Lemma/ -M Sentic_SONN_homer_lemma /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/BastText/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/Mulan/NoNeutral/Sentic/Lemma/ /cygdrive/d/Sentiment_Analysis/Emotion_Adrian/PredictionsNN/